spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: (username)
      password: (password)
      database: MusicPlayer
      authentication-database: admin

app:
  jwt:
    secret: (secret)
    expirationMs: 86400000

  spotify:
    clientId: (clientId)
    clientSecret: (clientSecret)

  youtube:
    api:
      key: (key)
